Refactor bin script formatting

diff --git a/bin/awx-run-playbooks b/bin/awx-run-playbooks
--- a/bin/awx-run-playbooks
+++ b/bin/awx-run-playbooks
@@ -9,209 +9,206 @@ SUCCESS=0
 PARAMS=$SUCCESS
 
 function check_requirement {
-    cmd=$1
-    command -v "${cmd}" >/dev/null 2>&1 || {
-        echo "${cmd} not found, aborting"
-        exit "${ERROR}"
-    }
+  cmd=$1
+  command -v "${cmd}" >/dev/null 2>&1 || {
+    echo "${cmd} not found, aborting"
+    exit "${ERROR}"
+  }
 }
 
 function array_contains {
-    local array="$1[@]"
-    local seeking=$2
-    local in=1
-    for element in "${!array}"; do
-        if [[ $element == "$seeking" ]]; then
-            in=0
-            break
-        fi
-    done
-    return $in
+  local array="$1[@]"
+  local seeking=$2
+  local in=1
+  for element in "${!array}"; do
+    if [[ $element == "$seeking" ]]; then
+      in=0
+      break
+    fi
+  done
+  return $in
 }
 
 function help {
-    echo "$0 OPTIONS <playbook> [ <playbook> ... ]"
-    echo
-    echo "OPTIONS:"
-    echo "   --host <awx host>"
-    echo "   --user <awx user>"
-    echo "   --pass <awx pass>"
-    echo "   --repo <awx project repository url>"
-    echo "  [--branch <awx project repository branch>]"
-    echo "  [--debug]"
+  echo "$0 OPTIONS <playbook> [ <playbook> ... ]"
+  echo
+  echo "OPTIONS:"
+  echo "   --host <awx host>"
+  echo "   --user <awx user>"
+  echo "   --pass <awx pass>"
+  echo "   --repo <awx project repository url>"
+  echo "  [--branch <awx project repository branch>]"
+  echo "  [--debug]"
 }
 
 function debug {
-    if [ "${DEBUG}" -eq "${TRUE}" ]; then
-        echo "$@"
-    fi
+  if [ "${DEBUG}" -eq "${TRUE}" ]; then
+    echo "$@"
+  fi
 }
-
-check_requirement tower-cli
-check_requirement jq
 
 # set defaults
 BRANCH="master"
+AWXCLI_BIN="tower-cli"
 AWXCLI_VERBOSE=""
+
+check_requirement "${AWXCLI_BIN}"
+check_requirement jq
 
 # parse options (https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash)
 POSITIONAL=()
 while [[ $# -gt 0 ]]
 do
-    key="$1"
+  key="$1"
 
-    case $key in
-        --host)
-            HOST="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --user)
-            _USER="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --pass)
-            _PASS="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --repo)
-            REPO="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --branch)
-            BRANCH="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --help)
-            help
-            exit ${SUCCESS}
-            ;;
-        --debug)
-            DEBUG=${TRUE}
-            AWXCLI_VERBOSE="--verbose"
-            shift # past argument
-            ;;
-        *)    # unknown option
-            POSITIONAL+=("$1") # save it in an array for later
-            shift # past argument
-            ;;
-    esac
+  case $key in
+    --host)
+      HOST="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --user)
+      _USER="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --pass)
+      _PASS="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --repo)
+      REPO="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --branch)
+      BRANCH="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --help)
+      help
+      exit ${SUCCESS}
+      ;;
+    --debug)
+      DEBUG=${TRUE}
+      AWXCLI_VERBOSE="--verbose"
+      shift # past argument
+      ;;
+    *)    # unknown option
+      POSITIONAL+=("$1") # save it in an array for later
+      shift # past argument
+      ;;
+  esac
 done
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
 # validate options
 if [ -z "${HOST}" ]; then
-    echo "--host <awx host> option is required"
-    PARAMS=${ERROR}
+  echo "--host <awx host> option is required"
+  PARAMS=${ERROR}
 fi
 if [ -z "${_USER}" ]; then
-    echo "--user <awx api user> option is required"
-    PARAMS=${ERROR}
+  echo "--user <awx api user> option is required"
+  PARAMS=${ERROR}
 fi
 if [ -z "${_PASS}" ]; then
-    echo "--pass <awx api password> option is required"
-    PARAMS=${ERROR}
+  echo "--pass <awx api password> option is required"
+  PARAMS=${ERROR}
 fi
 if [ -z "${REPO}" ]; then
-    echo "--repo <awx repo url> option is required"
-    PARAMS=${ERROR}
+  echo "--repo <awx repo url> option is required"
+  PARAMS=${ERROR}
 fi
 if [ "${#POSITIONAL[@]}" -eq 0 ]; then
-    echo "at least one playbook name must be specified"
-    exit ${ERROR}
+  echo "at least one playbook name must be specified"
+  exit ${ERROR}
 fi
 
 if [ "${PARAMS}" -eq "${ERROR}" ]; then
-    echo
-    help
-    exit ${PARAMS}
+  echo
+  help
+  exit ${PARAMS}
 fi
 
-tower-cli config host "${HOST}" >/dev/null 2>&1
-tower-cli config username "${_USER}" >/dev/null 2>&1
-tower-cli config password "${_PASS}" >/dev/null 2>&1
-tower-cli config format json >/dev/null 2>&1
+AWXCLI_GLOBAL_ARGS="-h ${HOST} -u ${_USER} -p ${_PASS} ${AWXCLI_VERBOSE}"
 
 # retrieve awx project ids
-if PRJ_JSON=$(tower-cli project list --scm-url "${REPO}" --scm-branch "${BRANCH}"); then
+if PRJ_JSON=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" project list --scm-url "${REPO}" --scm-branch "${BRANCH}"); then
 
-    PRJS=$(echo "${PRJ_JSON}" | jq -cr '.results[] | {name,id}')
+  PRJS=$(echo "${PRJ_JSON}" | jq -cr '.results[] | {name,id}')
 
-    if [ -z "${PRJS}" ]; then
+  if [ -z "${PRJS}" ]; then
 
-        echo "no projects found for repository ${REPO}"
+    echo "no projects found for repository ${REPO}"
 
-    else
+  else
 
-        for PRJ in ${PRJS}; do
+    for PRJ in ${PRJS}; do
 
-            PRJ_NAME=$(echo "$PRJ" | jq -r '.name')
-            PRJ_ID=$(echo "$PRJ" | jq -r '.id')
+      PRJ_NAME=$(echo "$PRJ" | jq -r '.name')
+      PRJ_ID=$(echo "$PRJ" | jq -r '.id')
 
-            if TPL_JSON=$(tower-cli job_template list); then
+      if TPL_JSON=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" job_template list); then
 
-                TPLS=$(echo "${TPL_JSON}" | jq -cr ".results[] | select(.summary_fields.project.id == ${PRJ_ID}) | {name,playbook}" )
+        TPLS=$(echo "${TPL_JSON}" | jq -cr ".results[] | select(.summary_fields.project.id == ${PRJ_ID}) | {name,playbook}" )
 
-                if [ -z "$TPLS" ]; then
+        if [ -z "$TPLS" ]; then
 
-                    echo "no templates found for project ${PRJ_NAME}"
+          echo "no templates found for project ${PRJ_NAME}"
 
-                else
+        else
 
-                    TPL_FOUND=${FALSE}
+          TPL_FOUND=${FALSE}
 
-                    for TPL in ${TPLS}; do
+          for TPL in ${TPLS}; do
 
-                        TPL_NAME=$(echo "$TPL" | jq -r '.name')
-                        TPL_PLAY=$(echo "$TPL" | jq -r '.playbook')
-
-                        if ( array_contains POSITIONAL "${TPL_PLAY}" ); then
-
-                            TPL_FOUND=${TRUE}
-
-                            if TPL_RUN=$(tower-cli job launch -J "${TPL_NAME}" --wait ${AWXCLI_VERBOSE}); then
-
-                                echo "ran template ${TPL_NAME}"
-
-                            else
-
-                                echo "error executing template ${TPL_NAME}"
-                                echo "${TPL_RUN}"
-                                exit ${ERROR}
-
-                            fi
-
-                        fi
-
-                    done
-
-                    if [ ${TPL_FOUND} -eq ${FALSE} ]; then
-
-                        echo "no matching templates found for project ${PRJ_NAME} with playbooks" "${POSITIONAL[@]}"
-
-                    fi
-
-                fi
+            TPL_NAME=$(echo "$TPL" | jq -r '.name')
+            TPL_PLAY=$(echo "$TPL" | jq -r '.playbook')
 
 
-            else
+              TPL_FOUND=${TRUE}
 
-                echo "unable to query template list from ${HOST}"
+              if TPL_RUN=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" job launch -J "${TPL_NAME}" --wait ${AWXCLI_VERBOSE}); then
+
+                echo "ran template ${TPL_NAME}"
+
+              else
+
+                echo "error executing template ${TPL_NAME}"
+                echo "${TPL_RUN}"
+                exit ${ERROR}
+
+              fi
 
             fi
 
-        done
-    fi
+          done
 
-    exit ${SUCCESS}
+          if [ ${TPL_FOUND} -eq ${FALSE} ]; then
+
+            echo "no matching templates found for project ${PRJ_NAME} with playbooks" "${POSITIONAL[@]}"
+
+          fi
+
+        fi
+
+
+      else
+
+        echo "unable to query template list from ${HOST}"
+
+      fi
+
+    done
+  fi
+
+  exit ${SUCCESS}
 
 else
 
-    echo "unable to query project list from ${HOST}"
-    exit ${ERROR}
+  echo "unable to query project list from ${HOST}"
+  exit ${ERROR}
 
 fi
diff --git a/bin/awx-run-templates b/bin/awx-run-templates
--- a/bin/awx-run-templates
+++ b/bin/awx-run-templates
@@ -9,199 +9,201 @@ SUCCESS=0
 PARAMS=$SUCCESS
 
 function check_requirement {
-    cmd=$1
-    command -v "${cmd}" >/dev/null 2>&1 || {
-        echo "${cmd} not found, aborting"
-        exit "${ERROR}"
-    }
+  cmd=$1
+  command -v "${cmd}" >/dev/null 2>&1 || {
+    echo "${cmd} not found, aborting"
+    exit "${ERROR}"
+  }
 }
 
 function array_contains {
-    local array="$1[@]"
-    local seeking=$2
-    local in=1
-    for element in "${!array}"; do
-        if [[ $element == "$seeking" ]]; then
-            in=0
-            break
-        fi
-    done
-    return $in
+  local array="$1[@]"
+  local seeking=$2
+  local in=1
+  for element in "${!array}"; do
+    if [[ $element == "$seeking" ]]; then
+      in=0
+      break
+    fi
+  done
+  return $in
 }
 
 function help {
-    echo "$0 OPTIONS <template> [ <template> ... ]"
-    echo
-    echo "OPTIONS:"
-    echo "   --host <awx host>"
-    echo "   --user <awx user>"
-    echo "   --pass <awx pass>"
-    echo "  [--inventory <awx inventory>]"
-    echo "  [--credential <awx credential> [--credential <awx credential>] ... ]"
-    echo "  [--opts <options>]"
-    echo "  [--debug]"
+  echo "$0 OPTIONS <template> [ <template> ... ]"
+  echo
+  echo "OPTIONS:"
+  echo "   --host <awx host>"
+  echo "   --user <awx user>"
+  echo "   --pass <awx pass>"
+  echo "  [--inventory <awx inventory>]"
+  echo "  [--credential <awx credential> [--credential <awx credential>] ... ]"
+  echo "  [--opts <options>]"
+  echo "  [--debug]"
 }
 
 function debug {
-    if [ "${DEBUG}" -eq "${TRUE}" ]; then
-        echo "$@"
-    fi
+  if [ "${DEBUG}" -eq "${TRUE}" ]; then
+    echo "$@"
+  fi
 }
 
 # set defaults
 AWXCLI_BIN="tower-cli"
 AWXCLI_VERBOSE=""
-AWXCLI_JOB="$AWXCLI_BIN job launch"
-AWXCLI_WF="$AWXCLI_BIN workflow_job launch"
+AWXCLI_JOB="${AWXCLI_BIN} job launch"
+AWXCLI_WF="${AWXCLI_BIN} workflow_job launch"
 _INVENTORY=""
 _CREDENTIAL=""
 _TAGS=""
 _SKIP_TAGS=""
 
-check_requirement "$AWXCLI_BIN"
+check_requirement "${AWXCLI_BIN}"
 check_requirement jq
 
 # parse options (https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash)
 POSITIONAL=()
 while [[ $# -gt 0 ]]
 do
-    key="$1"
+  key="$1"
 
-    case $key in
-        --host)
-            HOST="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --user)
-            _USER="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --pass)
-            _PASS="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --inventory)
-            _INVENTORY="--inventory $2"
-            shift # past argument
-            shift # past value
-            ;;
-        --credential)
-            _CREDENTIAL="${_CREDENTIAL} --credential $2"
-            shift # past argument
-            shift # past value
-            ;;
-        --tags)
-            _TAGS="--tags $2"
-            shift # past argument
-            shift # past value
-            ;;
-        --skip-tags)
-            _SKIP_TAGS="--skip-tags $2"
-            shift # past argument
-            shift # past value
-            ;;
-        --opts)
-            AWXCLI_JOB="${AWXCLI_JOB} $2"
-            AWXCLI_WF="${AWXCLI_WF} $2"
-            shift # past argument
-            shift # past value
-            ;;
-        --help)
-            help
-            exit ${SUCCESS}
-            ;;
-        --debug)
-            DEBUG=${TRUE}
-            AWXCLI_VERBOSE="--verbose"
-            shift # past argument
-            ;;
-        *)    # unknown option
-            POSITIONAL+=("$1") # save it in an array for later
-            shift # past argument
-            ;;
-    esac
+  case $key in
+    --host)
+      HOST="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --user)
+      _USER="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --pass)
+      _PASS="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --inventory)
+      _INVENTORY="--inventory $2"
+      shift # past argument
+      shift # past value
+      ;;
+    --credential)
+      _CREDENTIAL="${_CREDENTIAL} --credential $2"
+      shift # past argument
+      shift # past value
+      ;;
+    --tags)
+      _TAGS="--tags $2"
+      shift # past argument
+      shift # past value
+      ;;
+    --skip-tags)
+      _SKIP_TAGS="--skip-tags $2"
+      shift # past argument
+      shift # past value
+      ;;
+    --opts)
+      AWXCLI_JOB="${AWXCLI_JOB} $2"
+      AWXCLI_WF="${AWXCLI_WF} $2"
+      shift # past argument
+      shift # past value
+      ;;
+    --help)
+      help
+      exit ${SUCCESS}
+      ;;
+    --debug)
+      DEBUG=${TRUE}
+      AWXCLI_VERBOSE="--verbose"
+      shift # past argument
+      ;;
+    *)    # unknown option
+      POSITIONAL+=("$1") # save it in an array for later
+      shift # past argument
+      ;;
+  esac
 done
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
 # validate options
 if [ -z "${HOST}" ]; then
-    echo "--host <awx host> option is required"
-    PARAMS=${ERROR}
+  echo "--host <awx host> option is required"
+  PARAMS=${ERROR}
 fi
 if [ -z "${_USER}" ]; then
-    echo "--user <awx api user> option is required"
-    PARAMS=${ERROR}
+  echo "--user <awx api user> option is required"
+  PARAMS=${ERROR}
 fi
 if [ -z "${_PASS}" ]; then
-    echo "--pass <awx api password> option is required"
-    PARAMS=${ERROR}
+  echo "--pass <awx api password> option is required"
+  PARAMS=${ERROR}
 fi
 if [ "${#POSITIONAL[@]}" -eq 0 ]; then
-    echo "at least one template name must be specified"
-    exit ${ERROR}
+  echo "at least one template name must be specified"
+  exit ${ERROR}
 fi
 
 if [ "${PARAMS}" -eq "${ERROR}" ]; then
-    echo
-    help
-    exit ${PARAMS}
+  echo
+  help
+  exit ${PARAMS}
 fi
 
-AWXCLI_ARGS="-h ${HOST} -u ${_USER} -p ${_PASS} ${AWXCLI_VERBOSE} ${_TAGS} ${_SKIP_TAGS}"
+AWXCLI_GLOBAL_ARGS="-h ${HOST} -u ${_USER} -p ${_PASS} ${AWXCLI_VERBOSE}"
+AWXCLI_LOCAL_ARGS="${_TAGS} ${_SKIP_TAGS}"
+
 
 # retrieve template
 for TPL_NAME in "${POSITIONAL[@]}"; do
 
-    if $AWXCLI_BIN job_template get -n "${TPL_NAME}" ${AWXCLI_ARGS} >/dev/null 2>&1
+  if ${AWXCLI_BIN} job_template get -n "${TPL_NAME}" ${AWXCLI_GLOBAL_ARGS} >/dev/null 2>&1; then
 
-    then
+    echo "running template ${TPL_NAME}"
+    cmd="${AWXCLI_JOB} -J ${TPL_NAME} ${_INVENTORY} ${_CREDENTIAL} --wait ${AWXCLI_GLOBAL_ARGS} ${AWX_LOCAL_ARGS}"
+    debug "executing command: ${cmd}"
 
-        echo "running template ${TPL_NAME}"
-        debug "executing command: ${AWXCLI_JOB} -J ${TPL_NAME} ${AWXCLI_ARGS}"
+    if TPL_RUN=$(eval "${cmd}"); then
 
-        if TPL_RUN=$(${AWXCLI_JOB} ${_INVENTORY} ${_CREDENTIAL} -J "${TPL_NAME}" --wait ${AWXCLI_ARGS})
-
-        then
-
-            echo "ran template ${TPL_NAME}"
-
-        else
-
-            echo "error executing template ${TPL_NAME}"
-            echo "${TPL_RUN}"
-            exit ${ERROR}
-
-        fi
-
-    elif $AWXCLI_BIN workflow get -n "${TPL_NAME}" ${AWXCLI_ARGS} >/dev/null 2>&1
-
-    then
-
-        echo "running workflow ${TPL_NAME}"
-        debug "executing command: ${AWXCLI_WF} -W ${TPL_NAME} ${AWXCLI_ARGS}"
-
-        if TPL_RUN=$(${AWXCLI_WF} -W "${TPL_NAME}" --wait ${AWXCLI_ARGS})
-
-        then
-
-            echo "ran workflow ${TPL_NAME}"
-
-        else
-
-            echo "error executing workflow ${TPL_NAME}"
-            echo "${TPL_RUN}"
-            exit ${ERROR}
-
-        fi
+      echo "ran template ${TPL_NAME}"
 
     else
 
-        echo "could not find template or workflow '${TPL_NAME}'"
+      echo "error executing template ${TPL_NAME}"
+      echo "${TPL_RUN}"
+      exit ${ERROR}
 
     fi
+
+  elif ${AWXCLI_BIN} workflow get -n "${TPL_NAME}" ${AWXCLI_GLOBAL_ARGS} >/dev/null 2>&1; then
+
+    if [ -n "$AWX_LOCAL_ARGS" ]; then
+      "flags --tags/--skip-tags unavailable for workflow execution"
+    fi
+
+    echo "running workflow ${TPL_NAME}"
+    cmd="${AWXCLI_WF} -W "${TPL_NAME}" --wait ${AWXCLI_GLOBAL_ARGS}"
+    debug "executing command: ${cmd}"
+
+    if TPL_RUN=$(eval "$cmd")
+
+    then
+
+      echo "ran workflow ${TPL_NAME}"
+
+    else
+
+      echo "error executing workflow ${TPL_NAME}"
+      echo "${TPL_RUN}"
+      exit ${ERROR}
+
+    fi
+
+  else
+
+    echo "could not find template or workflow '${TPL_NAME}'"
+
+  fi
 
 done
 
diff --git a/bin/awx-update-inventories b/bin/awx-update-inventories
--- a/bin/awx-update-inventories
+++ b/bin/awx-update-inventories
@@ -10,249 +10,248 @@ PARAMS=${SUCCESS}
 FORCE=${FALSE}
 
 function check_requirement {
-    cmd=$1
-    command -v "${cmd}" >/dev/null 2>&1 || {
-        echo "${cmd} not found, aborting"
-        exit $ERROR
-    }
+  cmd=$1
+  command -v "${cmd}" >/dev/null 2>&1 || {
+    echo "${cmd} not found, aborting"
+    exit $ERROR
+  }
 }
 
 function help {
-    echo "$0 OPTIONS"
-    echo
-    echo "OPTIONS:"
-    echo "   --host <awx host>"
-    echo "   --user <awx user>"
-    echo "   --pass <awx pass>"
-    echo "   --repo <awx project repository url>"
-    echo "  [--force]"
-    echo "  [--branch <awx project repository branch>]"
-    echo "  [--debug]"
+  echo "$0 OPTIONS"
+  echo
+  echo "OPTIONS:"
+  echo "   --host <awx host>"
+  echo "   --user <awx user>"
+  echo "   --pass <awx pass>"
+  echo "   --repo <awx project repository url>"
+  echo "  [--force]"
+  echo "  [--branch <awx project repository branch>]"
+  echo "  [--debug]"
 }
 
 function debug {
-    if [ ${DEBUG} -eq ${TRUE} ]; then
-        echo "$@"
-    fi
+  if [ ${DEBUG} -eq ${TRUE} ]; then
+    echo "$@"
+  fi
 }
 
 function debug_inline {
-    if [ ${DEBUG} -eq ${TRUE} ]; then
-        echo -n "$@"
-    fi
+  if [ ${DEBUG} -eq ${TRUE} ]; then
+    echo -n "$@"
+  fi
 }
 
-check_requirement tower-cli
+AWXCLI_BIN=tower-cli
+
+check_requirement "${AWXCLI_BIN}"
 check_requirement jq
 
 # parse options (https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash)
 POSITIONAL=()
 while [[ $# -gt 0 ]]
 do
-    key="$1"
+  key="$1"
 
-    case $key in
-        --host)
-            HOST="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --user)
-            _USER="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --pass)
-            _PASS="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --repo)
-            REPO="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --branch)
-            BRANCH="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --from)
-            FROM="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --to)
-            TO="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --help)
-            help
-            exit ${SUCCESS}
-            ;;
-        --force)
-            FORCE="${TRUE}"
-            shift # past argument
-            ;;
-        --debug)
-            DEBUG="${TRUE}"
-            shift # past argument
-            ;;
-        *)  # unknown option
-            POSITIONAL+=("$1") # save it in an array for later
-            shift # past argument
-            ;;
-    esac
+  case $key in
+    --host)
+      HOST="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --user)
+      _USER="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --pass)
+      _PASS="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --repo)
+      REPO="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --branch)
+      BRANCH="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --from)
+      FROM="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --to)
+      TO="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --help)
+      help
+      exit ${SUCCESS}
+      ;;
+    --force)
+      FORCE="${TRUE}"
+      shift # past argument
+      ;;
+    --debug)
+      DEBUG="${TRUE}"
+      shift # past argument
+      ;;
+    *)  # unknown option
+      POSITIONAL+=("$1") # save it in an array for later
+      shift # past argument
+      ;;
+  esac
 done
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
 # validate options
 if [ -z "${HOST}" ]; then
-    echo "--host <awx host> option is required"
-    PARAMS="${ERROR}"
+  echo "--host <awx host> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${_USER}" ]; then
-    echo "--user <awx api user> option is required"
-    PARAMS="${ERROR}"
+  echo "--user <awx api user> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${_PASS}" ]; then
-    echo "--pass <awx api password> option is required"
-    PARAMS="${ERROR}"
+  echo "--pass <awx api password> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${REPO}" ]; then
-    echo "--repo <project reposority url> option is required"
-    PARAMS="${ERROR}"
+  echo "--repo <project reposority url> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ "${PARAMS}" == "${ERROR}" ]; then
-    PARAMS="${ERROR}"
+  PARAMS="${ERROR}"
 fi
 
 # set defaults
 if [ -z "${BRANCH}" ]; then
-    BRANCH="master"
+  BRANCH="master"
 fi
 if [ -z "${FROM}" ]; then
-    CI_COMMIT_BEFORE_SHA_DEFAULT="$(git rev-list --max-count=1 HEAD)"
-    FROM="${CI_COMMIT_BEFORE_SHA:-$CI_COMMIT_BEFORE_SHA_DEFAULT}"
-    debug "CI_COMMIT_BEFORE_SHA=${FROM}"
+  CI_COMMIT_BEFORE_SHA_DEFAULT="$(git rev-list --max-count=1 HEAD)"
+  FROM="${CI_COMMIT_BEFORE_SHA:-$CI_COMMIT_BEFORE_SHA_DEFAULT}"
+  debug "CI_COMMIT_BEFORE_SHA=${FROM}"
 fi
 if [ -z "${TO}" ]; then
-    CI_COMMIT_SHA_DEFAULT="$(git rev-list --max-count=2 HEAD | tail -1)"
-    TO="${CI_COMMIT_SHA:-$CI_COMMIT_SHA_DEFAULT}"
-    debug "CI_COMMIT_SHA=${TO}"
+  CI_COMMIT_SHA_DEFAULT="$(git rev-list --max-count=2 HEAD | tail -1)"
+  TO="${CI_COMMIT_SHA:-$CI_COMMIT_SHA_DEFAULT}"
+  debug "CI_COMMIT_SHA=${TO}"
 fi
 
 if [ "${PARAMS}" -eq "${ERROR}" ]; then
-    echo
-    help
-    exit ${PARAMS}
+  echo
+  help
+  exit ${PARAMS}
 fi
 
-tower-cli config host "${HOST}" >/dev/null 2>&1
-tower-cli config username "${_USER}" >/dev/null 2>&1
-tower-cli config password "${_PASS}" >/dev/null 2>&1
-tower-cli config format json >/dev/null 2>&1
+AWXCLI_GLOBAL_ARGS="-h ${HOST} -u ${_USER} -p ${_PASS} ${AWXCLI_VERBOSE}"
 
 # retrieve awx project ids
-if PRJ_JSON=$(tower-cli project list --scm-url "${REPO}" --scm-branch "${BRANCH}"); then
+if PRJ_JSON=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" project list --scm-url "${REPO}" --scm-branch "${BRANCH}"); then
 
-    PRJS=$(echo "${PRJ_JSON}" | jq -cr '.results')
+  PRJS=$(echo "${PRJ_JSON}" | jq -cr '.results')
 
-    if [ -z "${PRJS}" ]; then
+  if [ -z "${PRJS}" ]; then
 
-        echo "no projects found for repository ${REPO}"
+    echo "no projects found for repository ${REPO}"
 
-    else
+  else
 
-        _iter_jq() {
-            echo "${1}" | jq -r '.[]| @base64'
-        }
+    _iter_jq() {
+      echo "${1}" | jq -r '.[]| @base64'
+    }
 
-        for PRJB64 in $(_iter_jq "${PRJS}"); do
+    for PRJB64 in $(_iter_jq "${PRJS}"); do
 
-            _jq() {
-                echo "${1}" | base64 --decode | jq -r "${2}"
-            }
+      _jq() {
+        echo "${1}" | base64 --decode | jq -r "${2}"
+      }
 
-            PRJ_ID=$(_jq "${PRJB64}" ".id")
-            PRJ_NAME=$(_jq "${PRJB64}" ".name")
+      PRJ_ID=$(_jq "${PRJB64}" ".id")
+      PRJ_NAME=$(_jq "${PRJB64}" ".name")
 
-            # retrieve awx inventory source ids
-            INS_DATA=$(tower-cli inventory_source list --source-project "${PRJ_ID}" | jq ".results")
+      # retrieve awx inventory source ids
+      INS_DATA=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" inventory_source list --source-project "${PRJ_ID}" | jq ".results")
 
-            # retrieve diff
-            DIFF=$(git diff --name-only "${FROM}" "${TO}")
+      # retrieve diff
+      DIFF=$(git diff --name-only "${FROM}" "${TO}")
 
-            # get ids for inventory sources with source paths listed in git diff
-            INS_NAMES=()
-            debug "scanning project ${PRJ_NAME}"
-            for file in $DIFF; do
-                debug_inline "  scanning file ${file}"
+      # get ids for inventory sources with source paths listed in git diff
+      INS_NAMES=()
+      debug "scanning project ${PRJ_NAME}"
+      for file in $DIFF; do
+        debug_inline "  scanning file ${file}"
 
-                # show off some impressive jmespath fu
-                if [ ${FORCE} -eq ${TRUE} ]; then
-                    FILE_INS_NAMES=$(echo "$INS_DATA" |
-                                         jq -r "map(.name) | join(\" \")"
-                                  )
-                else
-                    FILE_INS_NAMES=$(echo "$INS_DATA" |
-                                         jq "map(.source_path as \$sp | select(\"${file}\" | startswith(\$sp)))" |
-                                         jq -r "map(.name) | join(\" \")"
-                                  )
-                fi
+        # show off some impressive jmespath fu
+        if [ ${FORCE} -eq ${TRUE} ]; then
+          FILE_INS_NAMES=$(echo "$INS_DATA" |
+                             jq -r "map(.name) | join(\" \")"
+                        )
+        else
+          FILE_INS_NAMES=$(echo "$INS_DATA" |
+                             jq "map(.source_path as \$sp | select(\"${file}\" | startswith(\$sp)))" |
+                             jq -r "map(.name) | join(\" \")"
+                        )
+        fi
 
-                # ensure set semantics for INS_NAMES list
-                if [ -n "${FILE_INS_NAMES}" ]; then
+        # ensure set semantics for INS_NAMES list
+        if [ -n "${FILE_INS_NAMES}" ]; then
 
-                    INS_NAME_FILTER=$(echo "${FILE_INS_NAMES[@]}" | uniq)
-                    IFS=', ' read -r -a INS_NAMES <<< "$INS_NAME_FILTER"
+          INS_NAME_FILTER=$(echo "${FILE_INS_NAMES[@]}" | uniq)
+          IFS=', ' read -r -a INS_NAMES <<< "$INS_NAME_FILTER"
 
-                    debug " [HIT]"
+          debug " [HIT]"
 
-                else
+        else
 
-                    debug " [MISS]"
+          debug " [MISS]"
 
-                fi
+        fi
 
-            done
+      done
 
-            # update inventory sources
-            if [ "${#INS_NAMES[@]}" -ne 0 ]; then
+      # update inventory sources
+      if [ "${#INS_NAMES[@]}" -ne 0 ]; then
 
-                for INS_NAME in "${INS_NAMES[@]}"; do
+        for INS_NAME in "${INS_NAMES[@]}"; do
 
-                    echo -n "updating inventory source ${INS_NAME}"
+          echo -n "updating inventory source ${INS_NAME}"
 
-                    if INS_UPDATE=$(tower-cli inventory_source update --wait "${INS_NAME}"); then
+          if INS_UPDATE=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" inventory_source update --wait "${INS_NAME}"); then
 
-                        echo " [OK]"
+            echo " [OK]"
 
-                    else
+          else
 
-                        echo " [ERROR]"
-                        echo "${INS_UPDATE}"
-                        exit ${ERROR}
+            echo " [ERROR]"
+            echo "${INS_UPDATE}"
+            exit ${ERROR}
 
-                    fi
-
-                done
-
-            else
-
-                echo "no updates found for inventory sources"
-
-            fi
+          fi
 
         done
 
-    fi
+      else
+
+        echo "no updates found for inventory sources"
+
+      fi
+
+    done
+
+  fi
 
 else
 
-    echo "unable to query project list from ${HOST}"
-    exit ${ERROR}
+  echo "unable to query project list from ${HOST}"
+  exit ${ERROR}
 
 fi
 
diff --git a/bin/awx-update-inventory b/bin/awx-update-inventory
--- a/bin/awx-update-inventory
+++ b/bin/awx-update-inventory
@@ -10,38 +10,40 @@ PARAMS=${SUCCESS}
 FORCE=${FALSE}
 
 function check_requirement {
-    cmd=$1
-    command -v "${cmd}" >/dev/null 2>&1 || {
-        echo "${cmd} not found, aborting"
-        exit $ERROR
-    }
+  cmd=$1
+  command -v "${cmd}" >/dev/null 2>&1 || {
+    echo "${cmd} not found, aborting"
+    exit $ERROR
+  }
 }
 
 function help {
-    echo "$0 OPTIONS"
-    echo
-    echo "OPTIONS:"
-    echo "   --host <awx host>"
-    echo "   --user <awx user>"
-    echo "   --pass <awx pass>"
-    echo "   --inventory <inventory name>"
-    echo "  [--organization <inventory organization>]"
-    echo "  [--debug]"
+  echo "$0 OPTIONS"
+  echo
+  echo "OPTIONS:"
+  echo "   --host <awx host>"
+  echo "   --user <awx user>"
+  echo "   --pass <awx pass>"
+  echo "   --inventory <inventory name>"
+  echo "  [--organization <inventory organization>]"
+  echo "  [--debug]"
 }
 
 function debug {
-    if [ ${DEBUG} -eq ${TRUE} ]; then
-        echo "$@"
-    fi
+  if [ ${DEBUG} -eq ${TRUE} ]; then
+    echo "$@"
+  fi
 }
 
 function debug_inline {
-    if [ ${DEBUG} -eq ${TRUE} ]; then
-        echo -n "$@"
-    fi
+  if [ ${DEBUG} -eq ${TRUE} ]; then
+    echo -n "$@"
+  fi
 }
 
-check_requirement tower-cli
+AWXCLI_BIN=tower-cli
+
+check_requirement "${AWXCLI_BIN}"
 check_requirement jq
 
 # parse options (https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash)
@@ -49,100 +51,97 @@ ORGANIZATION=""
 POSITIONAL=()
 while [[ $# -gt 0 ]]
 do
-    key="$1"
+  key="$1"
 
-    case $key in
-        --host)
-            HOST="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --user)
-            _USER="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --pass)
-            _PASS="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --inventory)
-            INVENTORY="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --organization)
-            ORGANIZATION="--organization $2"
-            shift # past argument
-            shift # past value
-            ;;
-        --help)
-            help
-            exit ${SUCCESS}
-            ;;
-        --force)
-            FORCE="${TRUE}"
-            shift # past argument
-            ;;
-        --debug)
-            DEBUG="${TRUE}"
-            shift # past argument
-            ;;
-        *)  # unknown option
-            POSITIONAL+=("$1") # save it in an array for later
-            shift # past argument
-            ;;
-    esac
+  case $key in
+    --host)
+      HOST="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --user)
+      _USER="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --pass)
+      _PASS="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --inventory)
+      INVENTORY="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --organization)
+      ORGANIZATION="--organization $2"
+      shift # past argument
+      shift # past value
+      ;;
+    --help)
+      help
+      exit ${SUCCESS}
+      ;;
+    --force)
+      FORCE="${TRUE}"
+      shift # past argument
+      ;;
+    --debug)
+      DEBUG="${TRUE}"
+      shift # past argument
+      ;;
+    *)  # unknown option
+      POSITIONAL+=("$1") # save it in an array for later
+      shift # past argument
+      ;;
+  esac
 done
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
 # validate options
 if [ -z "${HOST}" ]; then
-    echo "--host <awx host> option is required"
-    PARAMS="${ERROR}"
+  echo "--host <awx host> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${_USER}" ]; then
-    echo "--user <awx api user> option is required"
-    PARAMS="${ERROR}"
+  echo "--user <awx api user> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${_PASS}" ]; then
-    echo "--pass <awx api password> option is required"
-    PARAMS="${ERROR}"
+  echo "--pass <awx api password> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${INVENTORY}" ] && [ ${#POSITIONAL[@]} -lt 1 ]; then
-    echo "--inventory <inventory name> option or positional argument is required"
-    PARAMS="${ERROR}"
+  echo "--inventory <inventory name> option or positional argument is required"
+  PARAMS="${ERROR}"
 fi
 if [ "${PARAMS}" == "${ERROR}" ]; then
-    PARAMS="${ERROR}"
+  PARAMS="${ERROR}"
 fi
 
 # set defaults
 if [ "${PARAMS}" -eq "${ERROR}" ]; then
-    echo
-    help
-    exit ${PARAMS}
+  echo
+  help
+  exit ${PARAMS}
 fi
 
-tower-cli config host "${HOST}" >/dev/null 2>&1
-tower-cli config username "${_USER}" >/dev/null 2>&1
-tower-cli config password "${_PASS}" >/dev/null 2>&1
-tower-cli config format json >/dev/null 2>&1
+AWXCLI_GLOBAL_ARGS="-h ${HOST} -u ${_USER} -p ${_PASS} ${AWXCLI_VERBOSE}"
 
 # update inventory
 if [ -n "${INVENTORY}" ]; then
-  UPDATE_JOBS=$(tower-cli inventory batch_update -n "${INVENTORY}" "${ORGANIZATION}" | jq -r 'map(.id|tostring) | join(" ")')
+  UPDATE_JOBS=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" inventory batch_update -n "${INVENTORY}" "${ORGANIZATION}" | jq -r 'map(.id|tostring) | join(" ")')
   for job in $UPDATE_JOBS; do
     echo "waiting for job $job to complete"
-    tower-cli inventory_update wait $job
+    ${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" inventory_update wait $job
   done
 fi
 
 for inventory in "${POSITIONAL[@]}"; do
-  UPDATE_JOBS=$(tower-cli inventory batch_update -n "${inventory}" "${ORGANIZATION}" | jq -r 'map(.id|tostring) | join(" ")')
+  UPDATE_JOBS=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" inventory batch_update -n "${inventory}" "${ORGANIZATION}" | jq -r 'map(.id|tostring) | join(" ")')
   for job in $UPDATE_JOBS; do
     echo "waiting for job $job to complete"
-    tower-cli inventory_update wait $job
+    ${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" inventory_update wait $job
   done
 done
diff --git a/bin/awx-update-projects b/bin/awx-update-projects
--- a/bin/awx-update-projects
+++ b/bin/awx-update-projects
@@ -9,166 +9,164 @@ SUCCESS=0
 PARAMS=$SUCCESS
 
 function check_requirement {
-    cmd=$1
-    command -v "${cmd}" >/dev/null 2>&1 || {
-        echo "${cmd} not found, aborting"
-        exit $ERROR
-    }
+  cmd=$1
+  command -v "${cmd}" >/dev/null 2>&1 || {
+    echo "${cmd} not found, aborting"
+    exit $ERROR
+  }
 }
 
 function help {
-    echo "$0 OPTIONS"
-    echo
-    echo "OPTIONS:"
-    echo "   --host <awx host>"
-    echo "   --user <awx user>"
-    echo "   --pass <awx pass>"
-    echo "   --repo <awx project repository url>"
-    echo "  [--branch <awx project repository branch>]"
-    echo "  [--debug]"
+  echo "$0 OPTIONS"
+  echo
+  echo "OPTIONS:"
+  echo "   --host <awx host>"
+  echo "   --user <awx user>"
+  echo "   --pass <awx pass>"
+  echo "   --repo <awx project repository url>"
+  echo "  [--branch <awx project repository branch>]"
+  echo "  [--debug]"
 }
 
 function debug {
-    if [ ${DEBUG} -eq ${TRUE} ]; then
-        echo "$@"
-    fi
+  if [ ${DEBUG} -eq ${TRUE} ]; then
+    echo "$@"
+  fi
 }
 
-check_requirement tower-cli
+AWXCLI_BIN=tower-cli
+
+check_requirement "${AWXCLI_BIN}"
 check_requirement jq
 
 # parse options (https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash)
 POSITIONAL=()
 while [[ $# -gt 0 ]]
 do
-    key="$1"
+  key="$1"
 
-    case $key in
-        --host)
-            HOST="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --user)
-            _USER="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --pass)
-            _PASS="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --repo)
-            REPO="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --branch)
-            BRANCH="$2"
-            shift # past argument
-            shift # past value
-            ;;
-        --help)
-            help
-            exit ${SUCCESS}
-            ;;
-        --debug)
-            DEBUG="${TRUE}"
-            shift # past argument
-            ;;
-        *)  # unknown option
-            POSITIONAL+=("$1") # save it in an array for later
-            shift # past argument
-            ;;
-    esac
+  case $key in
+    --host)
+      HOST="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --user)
+      _USER="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --pass)
+      _PASS="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --repo)
+      REPO="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --branch)
+      BRANCH="$2"
+      shift # past argument
+      shift # past value
+      ;;
+    --help)
+      help
+      exit ${SUCCESS}
+      ;;
+    --debug)
+      DEBUG="${TRUE}"
+      shift # past argument
+      ;;
+    *)  # unknown option
+      POSITIONAL+=("$1") # save it in an array for later
+      shift # past argument
+      ;;
+  esac
 done
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
 # validate options
 if [ -z "${HOST}" ]; then
-    echo "--host <awx host> option is required"
-    PARAMS="${ERROR}"
+  echo "--host <awx host> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${_USER}" ]; then
-    echo "--user <awx api user> option is required"
-    PARAMS="${ERROR}"
+  echo "--user <awx api user> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${_PASS}" ]; then
-    echo "--pass <awx api password> option is required"
-    PARAMS="${ERROR}"
+  echo "--pass <awx api password> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${REPO}" ]; then
-    echo "--repo <project reposority url> option is required"
-    PARAMS="${ERROR}"
+  echo "--repo <project reposority url> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ "${PARAMS}" == "${ERROR}" ]; then
-    PARAMS="${ERROR}"
+  PARAMS="${ERROR}"
 fi
 if [ -z "${_PASS}" ]; then
-    echo "--pass <awx api password> option is required"
-    PARAMS="${ERROR}"
+  echo "--pass <awx api password> option is required"
+  PARAMS="${ERROR}"
 fi
 if [ "${PARAMS}" == "${ERROR}" ]; then
-    PARAMS="${ERROR}"
+  PARAMS="${ERROR}"
 fi
 
 # set defaults
 if [ -z "${BRANCH}" ]; then
-    BRANCH="master"
+  BRANCH="master"
 fi
 
 if [ "${PARAMS}" -eq "${ERROR}" ]; then
-    echo
-    help
-    exit ${PARAMS}
+  echo
+  help
+  exit ${PARAMS}
 fi
 
-
-tower-cli config host "${HOST}" >/dev/null 2>&1
-tower-cli config username "${_USER}" >/dev/null 2>&1
-tower-cli config password "${_PASS}" >/dev/null 2>&1
-tower-cli config format json >/dev/null 2>&1
+AWXCLI_GLOBAL_ARGS="-h ${HOST} -u ${_USER} -p ${_PASS} ${AWXCLI_VERBOSE}"
 
 # retrieve awx project ids
-if PRJ_JSON=$(tower-cli project list --scm-url "${REPO}" --scm-branch "${BRANCH}"); then
+if PRJ_JSON=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" project list --scm-url "${REPO}" --scm-branch "${BRANCH}"); then
 
-    PRJS=$(echo "${PRJ_JSON}" | jq -cr '.results[] | {name,organization}')
+  PRJS=$(echo "${PRJ_JSON}" | jq -cr '.results[] | {name,organization}')
 
-    if [ -z "${PRJS}" ]; then
+  if [ -z "${PRJS}" ]; then
 
-        echo "no projects found for repository ${REPO}"
+    echo "no projects found for repository ${REPO}"
 
-    else
+  else
 
-        for PRJ in ${PRJS}; do
+    for PRJ in ${PRJS}; do
 
-            PRJ_NAME=$(echo "$PRJ" | jq -r '.name')
-            PRJ_ORG=$(echo "$PRJ" | jq -r '.organization')
+      PRJ_NAME=$(echo "$PRJ" | jq -r '.name')
+      PRJ_ORG=$(echo "$PRJ" | jq -r '.organization')
 
-            echo -n "updating project ${PRJ_NAME}"
+      echo -n "updating project ${PRJ_NAME}"
 
-            if PRJ_UPDATE=$(tower-cli project update -n "${PRJ_NAME}" --organization "${PRJ_ORG}" --wait); then
+      if PRJ_UPDATE=$(${AWXCLI_BIN} "${AWXCLI_GLOBAL_ARGS}" project update -n "${PRJ_NAME}" --organization "${PRJ_ORG}" --wait); then
 
-                echo " [OK]"
+        echo " [OK]"
 
-            else
+      else
 
-                echo " [ERROR]"
-                echo "${PRJ_UPDATE}"
-                exit ${ERROR}
+        echo " [ERROR]"
+        echo "${PRJ_UPDATE}"
+        exit ${ERROR}
 
-            fi
+      fi
 
-        done
+    done
 
-    fi
+  fi
 
-    exit ${SUCCESS}
+  exit ${SUCCESS}
 
 else
 
-    echo "unable to query project list from ${HOST}"
-    exit ${ERROR}
+  echo "unable to query project list from ${HOST}"
+  exit ${ERROR}
 
 fi
