Add support for calling workflows to template run script

diff --git a/bin/awx-run-templates b/bin/awx-run-templates
--- a/bin/awx-run-templates
+++ b/bin/awx-run-templates
@@ -127,9 +127,15 @@ tower-cli config format json 2>&1 >/dev/null
 # retrieve template
 for TPL_NAME in "${POSITIONAL[@]}"; do
 
-    if $(tower-cli job_template get -n ${TPL_NAME})
+    if $(tower-cli job_template get -n ${TPL_NAME} 2>&1 >/dev/null)
 
-        if TPL_RUN=$(tower-cli job launch -J "${TPL_NAME}" --wait); then
+    then
+
+        echo "running template ${TPL_NAME}"
+
+        if TPL_RUN=$(tower-cli job launch -J "${TPL_NAME}" --wait 2>&1 >/dev/null)
+
+        then
 
             echo "ran template ${TPL_NAME}"
 
@@ -139,25 +145,31 @@ for TPL_NAME in "${POSITIONAL[@]}"; do
             echo "${TPL_RUN}"
             exit ${ERROR}
 
-        elif $(tower-cli workflow get -n ${TPL_NAME}); then
+        fi
 
-            if TPL_RUN=$(tower-cli workflow_job launch -J "${TPL_NAME}" --wait); then
+    elif $(tower-cli workflow get -n ${TPL_NAME} 2>&1 >/dev/null)
 
-                echo "ran workflow ${TPL_NAME}"
+    then
 
-            else
+        echo "running workflow ${TPL_NAME}"
 
-                echo "error executing workflow ${TPL_NAME}"
-                echo "${TPL_RUN}"
-                exit ${ERROR}
+        if TPL_RUN=$(tower-cli workflow_job launch -W $TPL_NAME --wait 2>&1 >/dev/null)
 
-            fi
+        then
+
+            echo "ran workflow ${TPL_NAME}"
 
         else
 
-            echo "could not find template or workflow '${TPL_NAME}'"
+            echo "error executing workflow ${TPL_NAME}"
+            echo "${TPL_RUN}"
+            exit ${ERROR}
 
         fi
+
+    else
+
+        echo "could not find template or workflow '${TPL_NAME}'"
 
     fi
 
